packages:
  - platform/wasm/pkg
  - packages/*

allowBuilds:
  core-js: true
  esbuild: true
  onnxruntime-node: true
  protobufjs: true
  sharp: false
  vue-demi: true

overrides:
  "@atproto/lex-builder": "alpha"
  "@atproto/lex-client": "alpha"
  "@atproto/lex-document": "alpha"
  "@atproto/lex-installer": "alpha"
  "@atproto/lex-resolver": "alpha"
  "@atproto/lex-schema": "alpha"
