packages:
  - apps/web
  - packages/*
  - packages/wasm/pkg

cargo:
  enabled: true

minimumReleaseAge: 0

allowBuilds:
  core-js: true
  esbuild: true
  onnxruntime-node: true
  protobufjs: true
  sharp: false
  vue-demi: true
  workerd: true
  "@nuxtjs/i18n@https://codeload.github.com/onmax/i18n/tar.gz/cf1fb91708422e749ed36d753c012e99ac2cd3ac": true

overrides:
  "@internationalized/date": "3.12.4"
  "@atproto/syntax": "0.0.0-spaces-alpha-20260913191958"
  "@atproto/lex-data": "0.0.0-spaces-alpha-20260913191958"
  "@atproto/lex-builder": "0.0.0-spaces-alpha-20260913191958"
  "@atproto/lex-client": "0.0.0-spaces-alpha-20260913191958"
  "@atproto/lex-cbor": "0.0.0-spaces-alpha-20260913191958"
  "@atproto/lex-document": "0.0.0-spaces-alpha-20260913191958"
  "@atproto/lex-installer": "0.0.0-spaces-alpha-20260913191958"
  "@atproto/lex-resolver": "0.0.0-spaces-alpha-20260913191958"
  "@atproto/lex-schema": "0.0.0-spaces-alpha-20260913191958"
