/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from "@atproto/lex-schema";

const $nsid = "com.atproto.moderation.defs";

type $nsid = typeof $nsid;

export { $nsid };

type ReasonType =
  | "com.atproto.moderation.defs#reasonSpam"
  | "com.atproto.moderation.defs#reasonViolation"
  | "com.atproto.moderation.defs#reasonMisleading"
  | "com.atproto.moderation.defs#reasonSexual"
  | "com.atproto.moderation.defs#reasonRude"
  | "com.atproto.moderation.defs#reasonOther"
  | "com.atproto.moderation.defs#reasonAppeal"
  | "tools.ozone.report.defs#reasonAppeal"
  | "tools.ozone.report.defs#reasonOther"
  | "tools.ozone.report.defs#reasonViolenceAnimal"
  | "tools.ozone.report.defs#reasonViolenceThreats"
  | "tools.ozone.report.defs#reasonViolenceGraphicContent"
  | "tools.ozone.report.defs#reasonViolenceGlorification"
  | "tools.ozone.report.defs#reasonViolenceExtremistContent"
  | "tools.ozone.report.defs#reasonViolenceTrafficking"
  | "tools.ozone.report.defs#reasonViolenceOther"
  | "tools.ozone.report.defs#reasonSexualAbuseContent"
  | "tools.ozone.report.defs#reasonSexualNCII"
  | "tools.ozone.report.defs#reasonSexualDeepfake"
  | "tools.ozone.report.defs#reasonSexualAnimal"
  | "tools.ozone.report.defs#reasonSexualUnlabeled"
  | "tools.ozone.report.defs#reasonSexualOther"
  | "tools.ozone.report.defs#reasonChildSafetyCSAM"
  | "tools.ozone.report.defs#reasonChildSafetyGroom"
  | "tools.ozone.report.defs#reasonChildSafetyPrivacy"
  | "tools.ozone.report.defs#reasonChildSafetyHarassment"
  | "tools.ozone.report.defs#reasonChildSafetyOther"
  | "tools.ozone.report.defs#reasonHarassmentTroll"
  | "tools.ozone.report.defs#reasonHarassmentTargeted"
  | "tools.ozone.report.defs#reasonHarassmentHateSpeech"
  | "tools.ozone.report.defs#reasonHarassmentDoxxing"
  | "tools.ozone.report.defs#reasonHarassmentOther"
  | "tools.ozone.report.defs#reasonMisleadingBot"
  | "tools.ozone.report.defs#reasonMisleadingImpersonation"
  | "tools.ozone.report.defs#reasonMisleadingSpam"
  | "tools.ozone.report.defs#reasonMisleadingScam"
  | "tools.ozone.report.defs#reasonMisleadingElections"
  | "tools.ozone.report.defs#reasonMisleadingOther"
  | "tools.ozone.report.defs#reasonRuleSiteSecurity"
  | "tools.ozone.report.defs#reasonRuleProhibitedSales"
  | "tools.ozone.report.defs#reasonRuleBanEvasion"
  | "tools.ozone.report.defs#reasonRuleOther"
  | "tools.ozone.report.defs#reasonSelfHarmContent"
  | "tools.ozone.report.defs#reasonSelfHarmED"
  | "tools.ozone.report.defs#reasonSelfHarmStunts"
  | "tools.ozone.report.defs#reasonSelfHarmSubstances"
  | "tools.ozone.report.defs#reasonSelfHarmOther"
  | l.UnknownString;

export type { ReasonType };

const reasonType = /*#__PURE__*/ l.string<{
  knownValues: [
    "com.atproto.moderation.defs#reasonSpam",
    "com.atproto.moderation.defs#reasonViolation",
    "com.atproto.moderation.defs#reasonMisleading",
    "com.atproto.moderation.defs#reasonSexual",
    "com.atproto.moderation.defs#reasonRude",
    "com.atproto.moderation.defs#reasonOther",
    "com.atproto.moderation.defs#reasonAppeal",
    "tools.ozone.report.defs#reasonAppeal",
    "tools.ozone.report.defs#reasonOther",
    "tools.ozone.report.defs#reasonViolenceAnimal",
    "tools.ozone.report.defs#reasonViolenceThreats",
    "tools.ozone.report.defs#reasonViolenceGraphicContent",
    "tools.ozone.report.defs#reasonViolenceGlorification",
    "tools.ozone.report.defs#reasonViolenceExtremistContent",
    "tools.ozone.report.defs#reasonViolenceTrafficking",
    "tools.ozone.report.defs#reasonViolenceOther",
    "tools.ozone.report.defs#reasonSexualAbuseContent",
    "tools.ozone.report.defs#reasonSexualNCII",
    "tools.ozone.report.defs#reasonSexualDeepfake",
    "tools.ozone.report.defs#reasonSexualAnimal",
    "tools.ozone.report.defs#reasonSexualUnlabeled",
    "tools.ozone.report.defs#reasonSexualOther",
    "tools.ozone.report.defs#reasonChildSafetyCSAM",
    "tools.ozone.report.defs#reasonChildSafetyGroom",
    "tools.ozone.report.defs#reasonChildSafetyPrivacy",
    "tools.ozone.report.defs#reasonChildSafetyHarassment",
    "tools.ozone.report.defs#reasonChildSafetyOther",
    "tools.ozone.report.defs#reasonHarassmentTroll",
    "tools.ozone.report.defs#reasonHarassmentTargeted",
    "tools.ozone.report.defs#reasonHarassmentHateSpeech",
    "tools.ozone.report.defs#reasonHarassmentDoxxing",
    "tools.ozone.report.defs#reasonHarassmentOther",
    "tools.ozone.report.defs#reasonMisleadingBot",
    "tools.ozone.report.defs#reasonMisleadingImpersonation",
    "tools.ozone.report.defs#reasonMisleadingSpam",
    "tools.ozone.report.defs#reasonMisleadingScam",
    "tools.ozone.report.defs#reasonMisleadingElections",
    "tools.ozone.report.defs#reasonMisleadingOther",
    "tools.ozone.report.defs#reasonRuleSiteSecurity",
    "tools.ozone.report.defs#reasonRuleProhibitedSales",
    "tools.ozone.report.defs#reasonRuleBanEvasion",
    "tools.ozone.report.defs#reasonRuleOther",
    "tools.ozone.report.defs#reasonSelfHarmContent",
    "tools.ozone.report.defs#reasonSelfHarmED",
    "tools.ozone.report.defs#reasonSelfHarmStunts",
    "tools.ozone.report.defs#reasonSelfHarmSubstances",
    "tools.ozone.report.defs#reasonSelfHarmOther",
  ];
}>();

export { reasonType };

/** Spam: frequent unwanted promotion, replies, mentions. Prefer new lexicon definition `tools.ozone.report.defs#reasonMisleadingSpam`. */
const reasonSpam = /*#__PURE__*/ l.token($nsid, "reasonSpam");

export { reasonSpam };

/** Spam: frequent unwanted promotion, replies, mentions. Prefer new lexicon definition `tools.ozone.report.defs#reasonMisleadingSpam`. */
const ReasonSpam = /*#__PURE__*/ reasonSpam.value;

/** Spam: frequent unwanted promotion, replies, mentions. Prefer new lexicon definition `tools.ozone.report.defs#reasonMisleadingSpam`. */
type ReasonSpam = typeof ReasonSpam;

export { ReasonSpam };

/** Direct violation of server rules, laws, terms of service. Prefer new lexicon definition `tools.ozone.report.defs#reasonRuleOther`. */
const reasonViolation = /*#__PURE__*/ l.token($nsid, "reasonViolation");

export { reasonViolation };

/** Direct violation of server rules, laws, terms of service. Prefer new lexicon definition `tools.ozone.report.defs#reasonRuleOther`. */
const ReasonViolation = /*#__PURE__*/ reasonViolation.value;

/** Direct violation of server rules, laws, terms of service. Prefer new lexicon definition `tools.ozone.report.defs#reasonRuleOther`. */
type ReasonViolation = typeof ReasonViolation;

export { ReasonViolation };

/** Misleading identity, affiliation, or content. Prefer new lexicon definition `tools.ozone.report.defs#reasonMisleadingOther`. */
const reasonMisleading = /*#__PURE__*/ l.token($nsid, "reasonMisleading");

export { reasonMisleading };

/** Misleading identity, affiliation, or content. Prefer new lexicon definition `tools.ozone.report.defs#reasonMisleadingOther`. */
const ReasonMisleading = /*#__PURE__*/ reasonMisleading.value;

/** Misleading identity, affiliation, or content. Prefer new lexicon definition `tools.ozone.report.defs#reasonMisleadingOther`. */
type ReasonMisleading = typeof ReasonMisleading;

export { ReasonMisleading };

/** Unwanted or mislabeled sexual content. Prefer new lexicon definition `tools.ozone.report.defs#reasonSexualUnlabeled`. */
const reasonSexual = /*#__PURE__*/ l.token($nsid, "reasonSexual");

export { reasonSexual };

/** Unwanted or mislabeled sexual content. Prefer new lexicon definition `tools.ozone.report.defs#reasonSexualUnlabeled`. */
const ReasonSexual = /*#__PURE__*/ reasonSexual.value;

/** Unwanted or mislabeled sexual content. Prefer new lexicon definition `tools.ozone.report.defs#reasonSexualUnlabeled`. */
type ReasonSexual = typeof ReasonSexual;

export { ReasonSexual };

/** Rude, harassing, explicit, or otherwise unwelcoming behavior. Prefer new lexicon definition `tools.ozone.report.defs#reasonHarassmentOther`. */
const reasonRude = /*#__PURE__*/ l.token($nsid, "reasonRude");

export { reasonRude };

/** Rude, harassing, explicit, or otherwise unwelcoming behavior. Prefer new lexicon definition `tools.ozone.report.defs#reasonHarassmentOther`. */
const ReasonRude = /*#__PURE__*/ reasonRude.value;

/** Rude, harassing, explicit, or otherwise unwelcoming behavior. Prefer new lexicon definition `tools.ozone.report.defs#reasonHarassmentOther`. */
type ReasonRude = typeof ReasonRude;

export { ReasonRude };

/** Reports not falling under another report category. Prefer new lexicon definition `tools.ozone.report.defs#reasonOther`. */
const reasonOther = /*#__PURE__*/ l.token($nsid, "reasonOther");

export { reasonOther };

/** Reports not falling under another report category. Prefer new lexicon definition `tools.ozone.report.defs#reasonOther`. */
const ReasonOther = /*#__PURE__*/ reasonOther.value;

/** Reports not falling under another report category. Prefer new lexicon definition `tools.ozone.report.defs#reasonOther`. */
type ReasonOther = typeof ReasonOther;

export { ReasonOther };

/** Appeal a previously taken moderation action */
const reasonAppeal = /*#__PURE__*/ l.token($nsid, "reasonAppeal");

export { reasonAppeal };

/** Appeal a previously taken moderation action */
const ReasonAppeal = /*#__PURE__*/ reasonAppeal.value;

/** Appeal a previously taken moderation action */
type ReasonAppeal = typeof ReasonAppeal;

export { ReasonAppeal };

/** Tag describing a type of subject that might be reported. */
type SubjectType = "account" | "record" | "chat" | l.UnknownString;

export type { SubjectType };

/** Tag describing a type of subject that might be reported. */
const subjectType = /*#__PURE__*/ l.string<{
  knownValues: ["account", "record", "chat"];
}>();

export { subjectType };
