/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from "@atproto/lex-schema";

import * as SimplespaceDefs from "./defs.defs";

const $nsid = "com.atproto.simplespace.createSpace";

type $nsid = typeof $nsid;

export { $nsid };

export const $params = /*#__PURE__*/ l.params();

export type $Params = l.InferOutput<typeof $params>;

export const $input = /*#__PURE__*/ l.jsonPayload({
  type: /*#__PURE__*/ l.string({ format: "nsid" }),
  skey: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string({ format: "record-key" })),
  policy: /*#__PURE__*/ l.typedUnion(
    [
      /*#__PURE__*/ l.typedRef<SimplespaceDefs.PublicPolicy>(
        (() => SimplespaceDefs.publicPolicy) as any,
      ),
      /*#__PURE__*/ l.typedRef<SimplespaceDefs.MemberListPolicy>(
        (() => SimplespaceDefs.memberListPolicy) as any,
      ),
      /*#__PURE__*/ l.typedRef<SimplespaceDefs.ManagingAppPolicy>(
        (() => SimplespaceDefs.managingAppPolicy) as any,
      ),
    ],
    false,
  ),
  appAccess: /*#__PURE__*/ l.typedUnion(
    [
      /*#__PURE__*/ l.typedRef<SimplespaceDefs.Open>((() => SimplespaceDefs.open) as any),
      /*#__PURE__*/ l.typedRef<SimplespaceDefs.AllowList>((() => SimplespaceDefs.allowList) as any),
    ],
    false,
  ),
});

export type $Input<B = l.BinaryData> = l.InferPayload<typeof $input, B>;
export type $InputBody<B = l.BinaryData> = l.InferPayloadBody<typeof $input, B>;

export const $output = /*#__PURE__*/ l.jsonPayload({
  uri: /*#__PURE__*/ l.string({ format: "space-ref" }),
});

export type $Output<B = l.BinaryData> = l.InferPayload<typeof $output, B>;
export type $OutputBody<B = l.BinaryData> = l.InferPayloadBody<typeof $output, B>;

/** Create a new space managed by the simplespace implementation. The space is anchored on the authenticated user's DID, who becomes the space owner. Requires auth, implemented by PDS. */
const main = /*#__PURE__*/ l.procedure($nsid, $params, $input, $output, [
  "SpaceAlreadyExists",
  "UnsupportedPolicy",
  "UnsupportedAppAccess",
]);

export { main };

const $lxm = $nsid;

type $lxm = typeof $lxm;

export { $lxm };
