/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from "@atproto/lex-schema";

const $nsid = "com.atproto.simplespace.defs";

type $nsid = typeof $nsid;

export { $nsid };

/** User access policy: any user may access the space. */
type PublicPolicy = { $type?: "com.atproto.simplespace.defs#publicPolicy" };

export type { PublicPolicy };

/** User access policy: any user may access the space. */
const publicPolicy = /*#__PURE__*/ l.typedObject<PublicPolicy>(
  $nsid,
  "publicPolicy",
  /*#__PURE__*/ l.object({}),
);

export { publicPolicy };

/** User access policy: only users on the space's member list may access it. */
type MemberListPolicy = {
  $type?: "com.atproto.simplespace.defs#memberListPolicy";
};

export type { MemberListPolicy };

/** User access policy: only users on the space's member list may access it. */
const memberListPolicy = /*#__PURE__*/ l.typedObject<MemberListPolicy>(
  $nsid,
  "memberListPolicy",
  /*#__PURE__*/ l.object({}),
);

export { memberListPolicy };

/** User access policy: the managing app is asked, via checkUserAccess, whether to authorize each user. */
type ManagingAppPolicy = {
  $type?: "com.atproto.simplespace.defs#managingAppPolicy";

  /**
   * Service identifier of the managing app: a DID with an optional service fragment (e.g. 'did:web:example.com#forum').
   */
  managingApp: string;
};

export type { ManagingAppPolicy };

/** User access policy: the managing app is asked, via checkUserAccess, whether to authorize each user. */
const managingAppPolicy = /*#__PURE__*/ l.typedObject<ManagingAppPolicy>(
  $nsid,
  "managingAppPolicy",
  /*#__PURE__*/ l.object({ managingApp: /*#__PURE__*/ l.string() }),
);

export { managingAppPolicy };

/** App access policy: any app may access the space. No client attestation required. */
type Open = { $type?: "com.atproto.simplespace.defs#open" };

export type { Open };

/** App access policy: any app may access the space. No client attestation required. */
const open = /*#__PURE__*/ l.typedObject<Open>($nsid, "open", /*#__PURE__*/ l.object({}));

export { open };

/** App access policy: only the named clients may access the space, evaluated against the attested client_id. */
type AllowList = {
  $type?: "com.atproto.simplespace.defs#allowList";

  /**
   * The OAuth client IDs permitted to access the space.
   */
  allowed: string[];
};

export type { AllowList };

/** App access policy: only the named clients may access the space, evaluated against the attested client_id. */
const allowList = /*#__PURE__*/ l.typedObject<AllowList>(
  $nsid,
  "allowList",
  /*#__PURE__*/ l.object({
    allowed: /*#__PURE__*/ l.array(/*#__PURE__*/ l.string()),
  }),
);

export { allowList };
