/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from "@atproto/lex-schema";

import * as SimplespaceDefs from "./defs.defs";

const $nsid = "com.atproto.simplespace.getSpace";

type $nsid = typeof $nsid;

export { $nsid };

export const $params = /*#__PURE__*/ l.params({
  space: /*#__PURE__*/ l.string({ format: "space-ref" }),
});

export type $Params = l.InferOutput<typeof $params>;

export const $output = /*#__PURE__*/ l.jsonPayload({
  uri: /*#__PURE__*/ l.string({ format: "space-ref" }),
  policy: /*#__PURE__*/ l.typedUnion(
    [
      /*#__PURE__*/ l.typedRef<SimplespaceDefs.PublicPolicy>(
        (() => SimplespaceDefs.publicPolicy) as any,
      ),
      /*#__PURE__*/ l.typedRef<SimplespaceDefs.MemberListPolicy>(
        (() => SimplespaceDefs.memberListPolicy) as any,
      ),
      /*#__PURE__*/ l.typedRef<SimplespaceDefs.ManagingAppPolicy>(
        (() => SimplespaceDefs.managingAppPolicy) as any,
      ),
    ],
    false,
  ),
  appAccess: /*#__PURE__*/ l.typedUnion(
    [
      /*#__PURE__*/ l.typedRef<SimplespaceDefs.Open>((() => SimplespaceDefs.open) as any),
      /*#__PURE__*/ l.typedRef<SimplespaceDefs.AllowList>((() => SimplespaceDefs.allowList) as any),
    ],
    false,
  ),
});

export type $Output<B = l.BinaryData> = l.InferPayload<typeof $output, B>;
export type $OutputBody<B = l.BinaryData> = l.InferPayloadBody<typeof $output, B>;

/** Describe a space managed by the simplespace implementation, including its configuration. Served by the space host. Requires either OAuth (for a caller with an account on this host) or a space credential (for a member hosted elsewhere); either way the caller must be authorized for the space. */
const main = /*#__PURE__*/ l.query($nsid, $params, $output, ["SpaceNotFound"]);

export { main };

const $lxm = $nsid;

type $lxm = typeof $lxm;

export { $lxm };
