/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

export * as repo from "./atproto/repo";
export * as simplespace from "./atproto/simplespace";
export * as space from "./atproto/space";
export * as label from "./atproto/label";
export * as moderation from "./atproto/moderation";
