/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from "@atproto/lex-schema";

const $nsid = "app.typbase.asset";

type $nsid = typeof $nsid;

export { $nsid };

/** Maps a reference path in a page (asset://...) to a blob stored in the space. Written by the member who uploaded the blob. */
type Main = {
  $type: "app.typbase.asset";

  /**
   * Page doc id that references the asset.
   */
  docId: string;

  /**
   * Reference path as used in Typst source, e.g. 'cover.png'.
   */
  ref: string;

  /**
   * The media blob.
   */
  blob: l.BlobRef;

  /**
   * Media mime type.
   */
  mime: string;

  /**
   * Blob size in bytes.
   */
  size: number;

  /**
   * Accessibility text.
   */
  alt?: string;
};

export type { Main };

/** Maps a reference path in a page (asset://...) to a blob stored in the space. Written by the member who uploaded the blob. */
const main = /*#__PURE__*/ l.record<"any", Main>(
  "any",
  $nsid,
  /*#__PURE__*/ l.object({
    docId: /*#__PURE__*/ l.string(),
    ref: /*#__PURE__*/ l.string(),
    blob: /*#__PURE__*/ l.blob(),
    mime: /*#__PURE__*/ l.string(),
    size: /*#__PURE__*/ l.integer(),
    alt: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string()),
  }),
);

export { main };

const $type = $nsid;

type $type = typeof $type;

export { $type };

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main);
export const $build = /*#__PURE__*/ main.build.bind(main);
export const $assert = /*#__PURE__*/ main.assert.bind(main);
export const $check = /*#__PURE__*/ main.check.bind(main);
export const $cast = /*#__PURE__*/ main.cast.bind(main);
export const $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main);
export const $matches = /*#__PURE__*/ main.matches.bind(main);
export const $parse = /*#__PURE__*/ main.parse.bind(main);
export const $safeParse = /*#__PURE__*/ main.safeParse.bind(main);
export const $validate = /*#__PURE__*/ main.validate.bind(main);
export const $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main);
