/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from "@atproto/lex-schema";

const $nsid = "app.typbase.config";

type $nsid = typeof $nsid;

export { $nsid };

/** Workspace metadata held in the space rather than in a Loro doc, so non-Typbase apps can read it without decoding CRDT state. */
type Main = {
  $type: "app.typbase.config";

  /**
   * Workspace name.
   */
  name: string;

  /**
   * Short description shown to members and third-party apps.
   */
  description?: string;

  /**
   * App-defined metadata (e.g. publish defaults). Not enforced beyond JSON validity.
   */
  publicInfo?: l.LexMap;

  /**
   * Optional workspace icon.
   */
  icon?: l.BlobRef;

  /**
   * Creation timestamp.
   */
  createdAt?: l.DatetimeString;
};

export type { Main };

/** Workspace metadata held in the space rather than in a Loro doc, so non-Typbase apps can read it without decoding CRDT state. */
const main = /*#__PURE__*/ l.record<"literal:self", Main>(
  "literal:self",
  $nsid,
  /*#__PURE__*/ l.object({
    name: /*#__PURE__*/ l.string({ maxLength: 100 }),
    description: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string({ maxLength: 500 })),
    publicInfo: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.lexMap()),
    icon: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.blob({ accept: ["image/*"], maxSize: 1000000 })),
    createdAt: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string({ format: "datetime" })),
  }),
);

export { main };

const $type = $nsid;

type $type = typeof $type;

export { $type };

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main);
export const $build = /*#__PURE__*/ main.build.bind(main);
export const $assert = /*#__PURE__*/ main.assert.bind(main);
export const $check = /*#__PURE__*/ main.check.bind(main);
export const $cast = /*#__PURE__*/ main.cast.bind(main);
export const $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main);
export const $matches = /*#__PURE__*/ main.matches.bind(main);
export const $parse = /*#__PURE__*/ main.parse.bind(main);
export const $safeParse = /*#__PURE__*/ main.safeParse.bind(main);
export const $validate = /*#__PURE__*/ main.validate.bind(main);
export const $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main);
