/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from "@atproto/lex-schema";

const $nsid = "app.typbase.post";

type $nsid = typeof $nsid;

export { $nsid };

/** A published note. Written to the author's public repo; the record is the canonical pointer to the rendered artifacts. Unpublishing deletes the record, firehose mirrors may retain copies. */
type Main = {
  $type: "app.typbase.post";

  /**
   * Note title.
   */
  title: string;

  /**
   * Plain-text summary for listings and feeds.
   */
  summary?: string;

  /**
   * Rendered HTML of the note.
   */
  html: l.BlobRef;

  /**
   * Optional rendered PDF.
   */
  pdf?: l.BlobRef;

  /**
   * The Typst source, for the curious and for re-publishing.
   */
  source: string;

  /**
   * Link back into the workspace source (space record URI or app deep link).
   */
  sourceUri: string;

  /**
   * Language codes.
   */
  langs?: string[];

  /**
   * Tags for feeds and discovery.
   */
  tags?: string[];
  createdAt?: l.DatetimeString;
  updatedAt?: l.DatetimeString;
};

export type { Main };

/** A published note. Written to the author's public repo; the record is the canonical pointer to the rendered artifacts. Unpublishing deletes the record, firehose mirrors may retain copies. */
const main = /*#__PURE__*/ l.record<"tid", Main>(
  "tid",
  $nsid,
  /*#__PURE__*/ l.object({
    title: /*#__PURE__*/ l.string({ maxLength: 400 }),
    summary: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string({ maxLength: 2000 })),
    html: /*#__PURE__*/ l.blob({ accept: ["text/html"] }),
    pdf: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.blob({ accept: ["application/pdf"] })),
    source: /*#__PURE__*/ l.string(),
    sourceUri: /*#__PURE__*/ l.string(),
    langs: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.array(/*#__PURE__*/ l.string({ maxLength: 16 })),
    ),
    tags: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.array(/*#__PURE__*/ l.string({ maxLength: 40 })),
    ),
    createdAt: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string({ format: "datetime" })),
    updatedAt: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string({ format: "datetime" })),
  }),
);

export { main };

const $type = $nsid;

type $type = typeof $type;

export { $type };

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main);
export const $build = /*#__PURE__*/ main.build.bind(main);
export const $assert = /*#__PURE__*/ main.assert.bind(main);
export const $check = /*#__PURE__*/ main.check.bind(main);
export const $cast = /*#__PURE__*/ main.cast.bind(main);
export const $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main);
export const $matches = /*#__PURE__*/ main.matches.bind(main);
export const $parse = /*#__PURE__*/ main.parse.bind(main);
export const $safeParse = /*#__PURE__*/ main.safeParse.bind(main);
export const $validate = /*#__PURE__*/ main.validate.bind(main);
export const $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main);
