/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from "@atproto/lex-schema";

const $nsid = "app.typbase.workspace";

type $nsid = typeof $nsid;

export { $nsid };

/** A local-first knowledge base workspace. The authority owns the workspace; members sync Loro documents through records in their own permissioned repos. */
const main = /*#__PURE__*/ l.space(
  $nsid,
  "any",
  "typbase Workspace",
  ["app.typbase.config", "app.typbase.update", "app.typbase.snapshot", "app.typbase.asset"],
  {
    description:
      "A local-first knowledge base workspace. The authority owns the workspace; members sync Loro documents through records in their own permissioned repos.",
  },
);

export { main };
