/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

export * as createSpace from "./simplespace/createSpace";
export * as defs from "./simplespace/defs";
export * as getSpace from "./simplespace/getSpace";
