/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

export * as createRecord from "./space/createRecord";
export * as deleteRecord from "./space/deleteRecord";
export * as getBlob from "./space/getBlob";
export * as getDelegationToken from "./space/getDelegationToken";
export * as getSpaceCredential from "./space/getSpaceCredential";
export * as listRepoOps from "./space/listRepoOps";
export * as listRepos from "./space/listRepos";
export * as putRecord from "./space/putRecord";
export * as registerNotify from "./space/registerNotify";
export * as defs from "./space/defs";
