projects:
  web: "apps/web"
  native: "apps/native"
  engine: "packages/engine"
  codemirror: "packages/codemirror"
  typing: "packages/typing"
  storage: "packages/storage"
  spaces: "packages/spaces"

defaultProject: "web"

pipeline:
  cacheLifetime: "7 days"

vcs:
  defaultBranch: "main"
  provider: "github"
