/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from "@atproto/lex-schema";

const $nsid = "com.atproto.space.getBlob";

type $nsid = typeof $nsid;

export { $nsid };

export const $params = /*#__PURE__*/ l.params({
  space: /*#__PURE__*/ l.string({ format: "space-ref" }),
  repo: /*#__PURE__*/ l.string({ format: "did" }),
  cid: /*#__PURE__*/ l.string({ format: "cid" }),
});

export type $Params = l.InferOutput<typeof $params>;

export const $output = /*#__PURE__*/ l.payload("*/*");

export type $Output<B = l.BinaryData> = l.InferPayload<typeof $output, B>;
export type $OutputBody<B = l.BinaryData> = l.InferPayloadBody<typeof $output, B>;

/** Get a blob referenced from a record in a permissioned space. Returns the full blob as originally uploaded. Blobs are not uploaded through this namespace: a space record references a blob uploaded via com.atproto.repo.uploadBlob, so a client writing blob-bearing records into a space needs a blob permission alongside its space permission. Use listBlobs to enumerate a repo's blobs in a space. Callable with either OAuth (for the authenticated user's own data) or a space credential (for syncing services). */
const main = /*#__PURE__*/ l.query($nsid, $params, $output, [
  "BlobNotFound",
  "SpaceNotFound",
  "RepoNotFound",
  "RepoTakendown",
  "RepoSuspended",
  "RepoDeactivated",
]);

export { main };

const $lxm = $nsid;

type $lxm = typeof $lxm;

export { $lxm };
