/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from "@atproto/lex-schema";

const $nsid = "com.atproto.space.getDelegationToken";

type $nsid = typeof $nsid;

export { $nsid };

export const $params = /*#__PURE__*/ l.params({
  space: /*#__PURE__*/ l.string({ format: "space-ref" }),
});

export type $Params = l.InferOutput<typeof $params>;

export const $output = /*#__PURE__*/ l.jsonPayload({
  token: /*#__PURE__*/ l.string(),
});

export type $Output<B = l.BinaryData> = l.InferPayload<typeof $output, B>;
export type $OutputBody<B = l.BinaryData> = l.InferPayloadBody<typeof $output, B>;

/** Mint a delegation token for a space, proving the requesting app is acting on the user's behalf. Exchanged with the space authority for a space credential. Served by the requesting user's PDS. Requires OAuth auth. */
const main = /*#__PURE__*/ l.query($nsid, $params, $output);

export { main };

const $lxm = $nsid;

type $lxm = typeof $lxm;

export { $lxm };
