/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from "@atproto/lex-schema";

const $nsid = "com.atproto.space.getSpaceCredential";

type $nsid = typeof $nsid;

export { $nsid };

export const $params = /*#__PURE__*/ l.params();

export type $Params = l.InferOutput<typeof $params>;

export const $input = /*#__PURE__*/ l.jsonPayload({
  space: /*#__PURE__*/ l.string({ format: "space-ref" }),
  clientAttestation: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string()),
});

export type $Input<B = l.BinaryData> = l.InferPayload<typeof $input, B>;
export type $InputBody<B = l.BinaryData> = l.InferPayloadBody<typeof $input, B>;

export const $output = /*#__PURE__*/ l.jsonPayload({
  credential: /*#__PURE__*/ l.string(),
});

export type $Output<B = l.BinaryData> = l.InferPayload<typeof $output, B>;
export type $OutputBody<B = l.BinaryData> = l.InferPayloadBody<typeof $output, B>;

/** Exchange a delegation token for a space credential. Called on the space authority, with the delegation token as the request's authorization token and a DPoP proof signed by the key to bind the credential to. The resulting space credential reads repos across the space. Requires a delegation token and DPoP proof, plus a client attestation when the space gates on app identity. */
const main = /*#__PURE__*/ l.procedure($nsid, $params, $input, $output, [
  "SpaceNotFound",
  "SpaceDeleted",
  "UserNotAuthorized",
  "AppNotAuthorized",
  "NotAuthorized",
  "InvalidDelegationToken",
  "InvalidClientAttestation",
]);

export { main };

const $lxm = $nsid;

type $lxm = typeof $lxm;

export { $lxm };
