/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from "@atproto/lex-schema";

const $nsid = "com.atproto.space.registerNotify";

type $nsid = typeof $nsid;

export { $nsid };

export const $params = /*#__PURE__*/ l.params();

export type $Params = l.InferOutput<typeof $params>;

export const $input = /*#__PURE__*/ l.jsonPayload({
  space: /*#__PURE__*/ l.string({ format: "space-ref" }),
  service: /*#__PURE__*/ l.string(),
});

export type $Input<B = l.BinaryData> = l.InferPayload<typeof $input, B>;
export type $InputBody<B = l.BinaryData> = l.InferPayloadBody<typeof $input, B>;

export const $output = /*#__PURE__*/ l.jsonPayload({
  expiresAt: /*#__PURE__*/ l.string({ format: "datetime" }),
});

export type $Output<B = l.BinaryData> = l.InferPayload<typeof $output, B>;
export type $OutputBody<B = l.BinaryData> = l.InferPayloadBody<typeof $output, B>;

/** Register a service to be notified of writes to any repo in a space. Called on the space host. The registering service is named by its service identifier rather than a bare URL, because notifyWrite is delivered with service auth addressed to that identifier; the delivery endpoint is resolved from the service's DID document. Authenticated with a space credential. Re-registering an existing service replaces its registration and extends the expiry. */
const main = /*#__PURE__*/ l.procedure($nsid, $params, $input, $output, [
  "SpaceNotFound",
  "ServiceNotResolvable",
]);

export { main };

const $lxm = $nsid;

type $lxm = typeof $lxm;

export { $lxm };
