import type { TypstState } from "@typbase/engine";
import type { WorkspaceStore } from "@typbase/storage";

import { publishPrelude, publishSyntaxTheme } from "~/lib/publishPrelude";

const encoder = new TextEncoder();

const README = `# Typbase project view

This directory is generated by the app; edits here are overwritten.

- \`lib.typ\`: the note stdlib (\`typbase.query\`, \`typbase.embed\`, ...).
- \`entries/<page.path>\`: the workspace prelude plus that page's source. Compile
  these, not the raw files at \`<page.path>\` next to them, because the raw files
  do not carry the prelude.
- \`query/\`, \`src/\`, \`blob/\`: data the app resolved while compiling. Files
  appear here after the app has requested them once.

Page sources live at their own path (\`pages/foo.typ\`, \`daily/2026-09-22.typ\`).
\`state/\` holds the app's CRDT snapshots; do not edit or delete it.

\`// %%\` lines are notebook cell markers. They are comments, so a notebook
compiles exactly like any other document.

\`\`\`sh
typst compile --root . --font-path <bundled fonts> typbase/entries/pages/foo.typ
\`\`\`
`;

export async function mirrorPageProject(
  store: WorkspaceStore,
  pageId: string,
  typstState?: TypstState,
): Promise<void> {
  const page = store.getPage(pageId);
  if (!page) return;

  // A dev server started before the last wasm build serves stale constructors;
  // skip the lib rather than failing the page load over the mirror.
  if (typstState && typeof typstState.typbaseLib === "function") {
    await store.writeProjectFile("typbase/lib.typ", encoder.encode(typstState.typbaseLib()));
  }

  const prelude = await publishPrelude(store.getSettings(), { theme: "light", paged: true });
  const source = await store.loadPageText(pageId);
  await store.writeProjectFile(
    `typbase/entries/${page.path}`,
    encoder.encode(`${prelude}\n${source}`),
  );
  // The prelude references this file for code-block syntax highlighting.
  const syntax = await publishSyntaxTheme(store.getSettings(), { theme: "light" });
  await store.writeProjectFile(syntax.path, encoder.encode(syntax.text));
  await store.writeProjectFile("typbase/README.md", encoder.encode(README));
}

/** Mirrors one resolved request file (query JSON, embed source, blob). */
export function mirrorRequestPayload(store: WorkspaceStore, path: string, bytes: Uint8Array): void {
  void store.writeProjectFile(path, bytes).catch((cause) => {
    console.warn("[typbase] project mirror write failed:", cause);
  });
}
