name: Publish npm Packages

on:
  release:
    types:
      - published
  workflow_call:
    inputs:
      tagName:
        description: Tag to publish from.
        required: false
        type: string
  workflow_dispatch:
    inputs:
      tagName:
        description: Tag to publish from; defaults to the current ref.
        required: false
        type: string

jobs:
  publish:
    name: 📦 Publish to npm
    runs-on: ubuntu-slim
    permissions:
      contents: read
      id-token: write
    steps:
      - name: 🔄 Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 1
          ref: ${{ inputs.tagName || github.event.release.tag_name || github.ref }}

      - name: 🦀 Setup Rust
        uses: moonrepo/setup-rust@abb2d32350334249b178c401e5ec5836e0cd88d3 # v1.3.0
        with:
          bins: wasm-pack
          targets: wasm32-unknown-unknown

      - name: 🌙 Setup moon
        uses: ./.github/actions/setup-moon

      - name: 📥 Install dependencies
        run: pnpm install --frozen-lockfile

      - name: 🔨 Build shared packages
        run: pnpm packages:build

      - name: 📦 Publish @typbase/wasm
        run: pnpm -C packages/wasm/pkg publish --no-git-checks --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: 📦 Publish @typbase/codemirror
        run: pnpm -C packages/codemirror publish --no-git-checks --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
